package puzzles.shortestpath.gui;

import java.awt.*;
import java.io.File;
import java.nio.charset.Charset;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import ai.Log;
import ai.gui.AIButton;
import ai.gui.AICanvas;
import ai.gui.AICheckBox;
import ai.gui.AIComboBox;
import ai.gui.AIContiniousScrollPane;
import ai.gui.AIGridCanvas;
import ai.gui.AIGui;
import ai.gui.AIPanel;
import ai.gui.AISlider;
import ai.gui.AISplitPane;
import ai.gui.AITextArea;
import ai.gui.AITextField;
import ai.models.grid.Board;
import algorithms.a_star.AStar;
import puzzles.shortestpath.Samples;
import puzzles.shortestpath.interfaces.ShortestPathButtonListener;

/**
 * Created by Patrick on 23.08.2014.
 */
public class ShortestPathGui extends AIGui {

  private static final String TAG = ShortestPathGui.class.getSimpleName();
  public static boolean DRAW_OUTLINES = true;
  public static boolean DRAW_CHILDREN = true;
  private AIGridCanvas drawingCanvas;
  private AIButton astarButton;
  private AIButton resetButton;
  private AIButton BFSButton;
  private AIButton DFSButton;
  private AIButton loadButton;
  private AIButton stepButton;

  private JPanel mainPanel;

  private AITextArea inputField;
  private AITextField statusField;
  private AITextField logField;
  private AIComboBox comboBox1;
  private AISlider stepSlider;
  private AICheckBox labelsCheckbox;
  private AIButton simulationButton;
  private AIContiniousScrollPane log;
  private AICheckBox shuffleChildrenCheckBox;
  private AICheckBox drawChildrenCheckBox;
  private AICheckBox drawOutlinesCheckBox;
  private AICheckBox stepCheckBox;
  private AIButton fromFileButton;

  private ShortestPathButtonListener listener;

  public ShortestPathGui() {

    astarButton.addActionListener(e -> listener.astarClicked());
    resetButton.addActionListener(e -> listener.resetClicked());
    loadButton.addActionListener(e -> listener.loadClicked());
    BFSButton.addActionListener(e -> listener.bfsClicked());
    DFSButton.addActionListener(e -> listener.dfsClicked());
    comboBox1.addActionListener(e -> {
      JComboBox cb = (JComboBox) e.getSource();
      int i = cb.getSelectedIndex();
      inputField.setText(Samples.getAstarSample(i));
    });
    stepButton.addActionListener(e -> listener.stepClicked());
    stepSlider.addChangeListener(new ChangeListener() {
      @Override
      public void stateChanged(ChangeEvent e) {
        Log.v(TAG, "slider event: " + e);
        AISlider slider = (AISlider) e.getSource();
        listener.stepChanged(slider.getValue());
      }
    });
    labelsCheckbox.addActionListener(e -> {
      AICheckBox checkbox = (AICheckBox) e.getSource();
      drawingCanvas.drawLabels(checkbox.isSelected());
    });
    simulationButton.addActionListener(e -> listener.simulationClicked());
    shuffleChildrenCheckBox.addActionListener(e -> {
      AICheckBox checkbox = (AICheckBox) e.getSource();
      AStar.SHUFFLE_CHILDREN = checkbox.isSelected();
    });
    drawChildrenCheckBox.addActionListener(e -> {
      AICheckBox checkbox = (AICheckBox) e.getSource();
      DRAW_CHILDREN = checkbox.isSelected();
    });
    drawOutlinesCheckBox.addActionListener(e -> {
      AICheckBox checkbox = (AICheckBox) e.getSource();
      ShortestPathGui.DRAW_OUTLINES = checkbox.isSelected();

    });
    stepCheckBox.addActionListener(e -> {
      AICheckBox checkbox = (AICheckBox) e.getSource();
      AStar.MANUAL_STEP = checkbox.isSelected();
    });

    buildFrame(mainPanel, log, statusField);
    fromFileButton.addActionListener(e -> {
      JFileChooser chooser = new JFileChooser("C:\\Dropbox\\code\\projects\\ai_prog\\samples");
      chooser.showOpenDialog(mainPanel);
      File file = chooser.getSelectedFile();
      inputField.setText(readFile(file.getPath(), Charset.defaultCharset()));
    });
  }

  public void setAdapter(Board adapter) {
    drawingCanvas.setAdapter(adapter);
    mainPanel.repaint();
  }

  public String getInput() {
    return inputField.getText().trim();
  }

  public void setListener(ShortestPathButtonListener listener) {
    this.listener = listener;
  }

  private void createUIComponents() {
    // TODO: place custom component creation code here
  }

  @Override
  protected int getDefaultCloseOperation() {
    return WindowConstants.DISPOSE_ON_CLOSE;
  }

  @Override
  protected Dimension getPreferredSize() {
    return new Dimension(900, 700);
  }

  @Override
  public JPanel getMainPanel() {
    return mainPanel;
  }

  @Override
  public AICanvas getDrawingCanvas() {
    return drawingCanvas;
  }

  @Override
  public AITextArea getInputField() {
    return inputField;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    mainPanel = new JPanel();
    mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), 0, 0));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 0, 0));
    mainPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2,
                                                                           com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                           com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                           | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                           null, null, null, 0, false));
    logField = new AITextField();
    panel1.add(logField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                          com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                          com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                          com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                          com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                          | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                          null, null, null, 0, false));
    statusField = new AITextField();
    statusField.setHorizontalAlignment(4);
    statusField.setText("status");
    panel1.add(statusField, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1,
                                                                             com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                             com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                             | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                             null, null, null, 0, false));
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(19, 1, new Insets(0, 0, 0, 0), 0, -1));
    mainPanel.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1,
                                                                           com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                           com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                           new Dimension(50, -1),
                                                                           new Dimension(120, -1), null, 0, false));
    stepButton = new AIButton();
    stepButton.setText("Step");
    panel2.add(stepButton, new com.intellij.uiDesigner.core.GridConstraints(9, 0, 1, 1,
                                                                            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                            com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                            | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                            null, null, null, 0, false));
    comboBox1 = new AIComboBox();
    final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
    defaultComboBoxModel1.addElement("Grid 1");
    defaultComboBoxModel1.addElement("Grid 2");
    defaultComboBoxModel1.addElement("Grid 3");
    defaultComboBoxModel1.addElement("Grid 4");
    defaultComboBoxModel1.addElement("Grid 5");
    defaultComboBoxModel1.addElement("Grid 6");
    defaultComboBoxModel1.addElement("Grid 7");
    defaultComboBoxModel1.addElement("Grid 8");
    defaultComboBoxModel1.addElement("Grid 9");
    comboBox1.setModel(defaultComboBoxModel1);
    panel2.add(comboBox1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                           com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                           com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                           null, null, null, 0, false));
    inputField = new AITextArea();
    panel2.add(inputField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 2, 1,
                                                                            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                            com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                            null, null, null, 0, false));
    astarButton = new AIButton();
    astarButton.setText("A*");
    panel2.add(astarButton, new com.intellij.uiDesigner.core.GridConstraints(11, 0, 1, 1,
                                                                             com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                             com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                             | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                             null, null, null, 0, false));
    BFSButton = new AIButton();
    BFSButton.setText("BFS");
    panel2.add(BFSButton, new com.intellij.uiDesigner.core.GridConstraints(12, 0, 1, 1,
                                                                           com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                           com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                           | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                           null, null, null, 0, false));
    DFSButton = new AIButton();
    DFSButton.setText("DFS");
    panel2.add(DFSButton, new com.intellij.uiDesigner.core.GridConstraints(13, 0, 1, 1,
                                                                           com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                           com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                           | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                           com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                           null, null, null, 0, false));
    loadButton = new AIButton();
    loadButton.setText("Load");
    panel2.add(loadButton, new com.intellij.uiDesigner.core.GridConstraints(16, 0, 1, 1,
                                                                            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                            com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                            | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                            null, null, null, 0, false));
    resetButton = new AIButton();
    resetButton.setText("Reset");
    panel2.add(resetButton, new com.intellij.uiDesigner.core.GridConstraints(18, 0, 1, 1,
                                                                             com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                             com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                             | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                             com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                             null, null, null, 0, false));
    final AIPanel aIPanel1 = new AIPanel();
    panel2.add(aIPanel1, new com.intellij.uiDesigner.core.GridConstraints(10, 0, 1, 1,
                                                                          com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                          com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                          1, 1, null, new Dimension(-1, 10),
                                                                          new Dimension(-1, 10), 0, false));
    final AIPanel aIPanel2 = new AIPanel();
    panel2.add(aIPanel2, new com.intellij.uiDesigner.core.GridConstraints(15, 0, 1, 1,
                                                                          com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                          com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                          1, 1, null, new Dimension(-1, 10),
                                                                          new Dimension(-1, 10), 0, false));
    stepSlider = new AISlider();
    stepSlider.setMajorTickSpacing(100);
    stepSlider.setMaximum(500);
    stepSlider.setMinimum(1);
    stepSlider.setMinorTickSpacing(50);
    stepSlider.setPaintLabels(false);
    stepSlider.setPaintTrack(true);
    stepSlider.setSnapToTicks(true);
    stepSlider.setValueIsAdjusting(true);
    panel2.add(stepSlider, new com.intellij.uiDesigner.core.GridConstraints(8, 0, 1, 1,
                                                                            com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                            com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                            1,
                                                                            com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                            null, null, null, 0, false));
    labelsCheckbox = new AICheckBox();
    labelsCheckbox.setSelected(false);
    labelsCheckbox.setText("Labels");
    panel2.add(labelsCheckbox, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1,
                                                                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                1,
                                                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                null, null, null, 0, false));
    simulationButton = new AIButton();
    simulationButton.setText("Simulation");
    panel2.add(simulationButton, new com.intellij.uiDesigner.core.GridConstraints(14, 0, 1, 1,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                  | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                  null, null, null, 0, false));
    shuffleChildrenCheckBox = new AICheckBox();
    shuffleChildrenCheckBox.setText("Shuffle Children");
    panel2.add(shuffleChildrenCheckBox, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1,
                                                                                         com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                         com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                                         com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                         | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                         com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                         | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                         null, null, null, 0, false));
    drawChildrenCheckBox = new AICheckBox();
    drawChildrenCheckBox.setText("Draw Children");
    panel2.add(drawChildrenCheckBox, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                      | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                      | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                      null, null, null, 0, false));
    drawOutlinesCheckBox = new AICheckBox();
    drawOutlinesCheckBox.setText("Outlines");
    panel2.add(drawOutlinesCheckBox, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                      | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                      com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                      | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                      null, null, null, 0, false));
    stepCheckBox = new AICheckBox();
    stepCheckBox.setText("Should step");
    panel2.add(stepCheckBox, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1,
                                                                              com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                              com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                              com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                              | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                              com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                              | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                              null, null, null, 0, false));
    fromFileButton = new AIButton();
    fromFileButton.setText("From File");
    panel2.add(fromFileButton, new com.intellij.uiDesigner.core.GridConstraints(17, 0, 1, 1,
                                                                                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                                null, null, null, 0, false));
    final AISplitPane aISplitPane1 = new AISplitPane();
    aISplitPane1.setContinuousLayout(false);
    aISplitPane1.setOneTouchExpandable(true);
    aISplitPane1.setOrientation(0);
    aISplitPane1.setResizeWeight(0.8);
    mainPanel.add(aISplitPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                 | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                 com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                 | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                 null, null, null, 0, false));
    log = new AIContiniousScrollPane();
    aISplitPane1.setRightComponent(log);
    drawingCanvas = new AIGridCanvas();
    drawingCanvas.setLayout(new GridBagLayout());
    aISplitPane1.setLeftComponent(drawingCanvas);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }
}